### ISSUE TITLE
i like it!

### ISSUE THREAD

**Issue by shavedkoala** [plp13/qman#4]
Hello!

Big thanks for this program, like it very much.

I had small issue with my setup - I had to remove `MANROFFOPT="-c"` from my env (used it for colored man pages). With it, qman was broken. So if anyone comes asking with same mystery issue "qman ugly/broken"...
I switched to `GROFF_NO_SGR=1` in my env, so my old `man` still paints colors (if i ever need it), and I see you are setting it up too, inside program.

Also, during install on archlinux from AUR, I was a bit shocked when it told me it needs to install all of haskell :) I understand it is pandoc for your markdown manual, but reading through dependencies I expected few packages as usual and got immediately suspicious of some shady stuff going on... You might put some warning in README.
 
Anyway, thanks!

Packages installed:
[PACMAN] Running 'pacman --database --asdeps -- ninja python-tqdm meson numactl ghc-libs haskell-lua haskell-hslua-core haskell-hslua-marshalling haskell-isocline haskell-hslua-repl hslua-cli haskell-dlist haskell-transformers-compat haskell-glob haskell-primitive haskell-vector-stream haskell-vector haskell-zlib haskell-juicypixels haskell-sha haskell-base-orphans haskell-onetuple haskell-erf haskell-splitmix haskell-random haskell-quickcheck haskell-data-array-byte haskell-ghc-bignum-orphans haskell-os-string haskell-hashable haskell-integer-logarithms haskell-scientific haskell-attoparsec haskell-base-compat haskell-base-compat-batteries haskell-data-fix haskell-generically haskell-tagged haskell-foldable1-classes-compat haskell-indexed-traversable haskell-unordered-containers haskell-indexed-traversable-instances haskell-distributive haskell-comonad haskell-th-abstraction haskell-bifunctors haskell-statevar haskell-contravariant haskell-semigroupoids haskell-assoc haskell-these haskell-semialign haskell-strict haskell-text-short haskell-time-compat haskell-uuid-types haskell-witherable haskell-aeson haskell-attoparsec-aeson haskell-cmdargs haskell-aeson-pretty haskell-base64-bytestring haskell-blaze-builder haskell-blaze-markup haskell-blaze-html haskell-case-insensitive haskell-data-default-class haskell-data-default-instances-containers haskell-data-default-instances-dlist haskell-old-locale haskell-data-default-instances-old-locale haskell-data-default haskell-file-embed haskell-syb haskell-pandoc-types haskell-safe haskell-text-icu haskell-th-lift haskell-th-lift-instances haskell-unicode-collation haskell-uniplate haskell-split haskell-bitvec haskell-vector-algorithms haskell-mono-traversable haskell-unliftio-core haskell-resourcet haskell-conduit haskell-async haskell-network haskell-streaming-commons haskell-typed-process haskell-conduit-extra haskell-xml-types haskell-xml-conduit haskell-citeproc haskell-unicode-data haskell-unicode-transforms haskell-commonmark haskell-emojis haskell-th-compat haskell-network-uri haskell-commonmark-extensions haskell-commonmark-pandoc haskell-basement haskell-hourglass haskell-memory haskell-asn1-types haskell-asn1-encoding haskell-asn1-parse haskell-crypton haskell-pem haskell-crypton-x509 haskell-crypton-x509-store haskell-crypton-x509-system haskell-crypton-x509-validation haskell-cereal haskell-socks haskell-old-time haskell-unix-time haskell-tls haskell-crypton-connection haskell-doclayout haskell-base16-bytestring haskell-text-conversions haskell-doctemplates haskell-gridtables haskell-haddock-library haskell-cookie haskell-http-types haskell-appar haskell-byteorder haskell-iproute haskell-mime-types haskell-http-client haskell-http-client-tls haskell-ipynb haskell-jira-wiki-markup haskell-lexer haskell-pretty-show haskell-colour haskell-utf8-string haskell-skylighting-core haskell-ansi-terminal-types haskell-ansi-terminal haskell-skylighting-format-ansi haskell-skylighting-format-blaze-html haskell-skylighting-format-context haskell-skylighting-format-latex haskell-skylighting haskell-tagsoup haskell-temporary haskell-typst-symbols haskell-xml haskell-texmath haskell-only haskell-cassava haskell-digits haskell-ordered-containers haskell-regex-base haskell-regex-tdfa haskell-prettyprinter haskell-toml-parser haskell-libyaml haskell-ansi-wl-pprint haskell-optparse-applicative haskell-yaml haskell-typst haskell-digest haskell-zip-archive haskell-pandoc haskell-hslua-aeson haskell-hslua-classes haskell-hslua-typing haskell-hslua-objectorientation haskell-hslua-packaging haskell-hslua haskell-hslua-module-doclayout haskell-hslua-module-path haskell-hslua-module-system haskell-hslua-module-text haskell-hslua-module-version haskell-hslua-list haskell-hslua-module-zip lua-lpeg haskell-lpeg haskell-pandoc-lua-marshal haskell-pandoc-lua-engine haskell-type-equality haskell-constraints haskell-attoparsec-iso8601 haskell-http-api-data haskell-http-media haskell-transformers-base haskell-monad-control haskell-mmorph haskell-sop-core haskell-boring haskell-dec haskell-some haskell-singleton-bool haskell-vault haskell-servant haskell-wai haskell-http-date haskell-unix-compat haskell-auto-update haskell-easy-file haskell-fast-logger haskell-wai-logger haskell-bsb-http-chunked haskell-network-byte-order haskell-psqueues haskell-safe-exceptions haskell-unliftio haskell-time-manager haskell-http2 haskell-recv haskell-simple-sendfile haskell-word8 haskell-warp haskell-call-stack haskell-hunit haskell-wai-extra haskell-wai-app-static haskell-servant-server haskell-base-unicode-symbols haskell-wai-cors haskell-pandoc-server pandoc-cli python-cogapp'

**Comment by plp13** [comment]
Hello, and thank you for your kind words.

I added a setenv() to reset MANROFFOPT to an empty string before calling /bin/man. Hopefully, this fixes the MANROFFOPT="-c" problem.

I also added a warning about `pandoc`'s dependencies to README.md. (Though, ideally, in future perhaps we should provide a pre-built manual page to avoid installing all that Haskell nonsense entirely.)

Thanks again!
